### ISSUE TITLE
24-hour time not working in some regions

### ISSUE THREAD

**Issue by amiantos** [amiantos/multiclock#2]
Seems like 24 hour time doesn't work in some cases https://twitter.com/arnz8o8/status/1480238572498268161?s=21

**Comment by martinh2011** [comment]
Same here. macOS 12.1v uses "Englis"h as primary language, but "German" region settings, i.e. time format should be 24h

**Comment by amiantos** [comment]
This'll make it out for 1.1, which maybe I'll take care of over the weekend.

**Comment by amiantos** [comment]
1.1 is out: https://github.com/amiantos/multiclock/releases/tag/screensaver-1.1
